name = "Thrift"
uuid = "8d9c9c80-f77e-5080-9541-c6f69d204e22"
version = "0.6.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
BinaryProvider = ">= 0.5.1"
julia = "1"
